"""Pure domain types and enums (no Qt/SQLite/filesystem side effects)."""

from koffer.domain.enums import (
    AnalysisRunState,
    ClassificationDimension,
    ClassificationSource,
    CollectionSortMode,
    ExclusionPatternType,
    JobItemState,
    JobState,
    JobType,
    SampleAvailability,
    ScanMode,
    SourceStatus,
    SuggestionStatus,
)
from koffer.domain.errors import (
    ApplicationError,
    NotFoundError,
    PathUnavailableError,
    UnsupportedOperationError,
    ValidationError,
)
from koffer.domain.ids import EntityId, new_entity_id
from koffer.domain.models import (
    Classification,
    Collection,
    ExclusionPreview,
    ExclusionRule,
    Job,
    Sample,
    Source,
    Suggestion,
    TechnicalMetadata,
)
from koffer.domain.query import (
    DEFAULT_PAGE_LIMIT,
    NumericRange,
    Page,
    PageRequest,
    SampleFilters,
    SampleQuery,
    SampleRow,
    SavedSearch,
    SortDirection,
    SortField,
    SortSpec,
)
from koffer.domain.timestamps import TIMESTAMP_CONVENTION, utc_now_iso

__all__ = [
    "DEFAULT_PAGE_LIMIT",
    "TIMESTAMP_CONVENTION",
    "AnalysisRunState",
    "ApplicationError",
    "Classification",
    "ClassificationDimension",
    "ClassificationSource",
    "Collection",
    "CollectionSortMode",
    "EntityId",
    "ExclusionPatternType",
    "ExclusionPreview",
    "ExclusionRule",
    "Job",
    "JobItemState",
    "JobState",
    "JobType",
    "NotFoundError",
    "NumericRange",
    "Page",
    "PageRequest",
    "PathUnavailableError",
    "Sample",
    "SampleAvailability",
    "SampleFilters",
    "SampleQuery",
    "SampleRow",
    "SavedSearch",
    "ScanMode",
    "SortDirection",
    "SortField",
    "SortSpec",
    "Source",
    "SourceStatus",
    "Suggestion",
    "SuggestionStatus",
    "TechnicalMetadata",
    "UnsupportedOperationError",
    "ValidationError",
    "new_entity_id",
    "utc_now_iso",
]
